[package]
name = "squashfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
# byteorder = "1.4.3"
binread = "2.2.0"
xz2 = "0.1.7"
flate2 = "1.0.24"